### ISSUE TITLE
Confused about the server name

### ISSUE THREAD

**Issue by spidy0x0** [tsani/jerrington.me#8]
hey bud,i am really confused about server_name section in the nginx block.Do i put in any random url there or i need to buy a new domain? 🤔

**Comment by tsani** [comment]
In my case, I have many sites hosted by one nginx instance, so nginx matches the HTTP `Host` header sent by the browser against the various `server_name`s that I have set in order to figure out which site to display. If you are only hosting one site with nginx, then I believe you can leave the `server_name` out.
